# Generated by Django 3.2.9 on 2021-11-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='pub_date',
        ),
    ]
