# Generated by Django 3.2.9 on 2021-11-14 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_player_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
