# Generated by Django 3.2.9 on 2021-11-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_player_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.player')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.season')),
            ],
        ),
        migrations.CreateModel(
            name='Appearances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearances', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.player')),
                ('season_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.season')),
            ],
        ),
    ]
